using PhysicalCountsHub.Common.API.ServiceContracts;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PhysicalCountsHub.Client.SampleApp
{
    class SampleProductDataSource : IProductDataSource
    {
        public async Task<Dictionary<ulong, string>> GetMasterList()
        {
            await Task.Delay(1000 * 3);

            //var a = 0;
            //var b = 23 / a;

            return new Dictionary<ulong, string>
            {                
                {  1, "NESCAFE DECAFRESEAL9" },
                {  2, "NESCAFE DECAFRESEAL4" },
                {  3, "BEARBRAND CHOCO 150GX40" },
                {  4, "BEARBRANDCHCOSWK29GX128" },
                {  5, "BEARBRAND MILK 1.6KGX10" },
                {  6, "KITKAT CHNKYBNDLS 11" },
                {  7, "MILO NUTRI UP 390GX1" },
                {  8, "MILO NUTRI UP 24GX14" },
                {  9, "NESTOKID FOUR 700GX10" },
                { 10, "NESFRUTA GUYABANO 25GX144" },
                { 11, "KITKAT2F17GX6SFRBENC" },
                { 12, "COFFEEMATE STAND UP POUCH" },
                { 13, "COFFEEMATE ORIG 170GX60" },
                { 14, "COFFEEMATE 290GX40" },
                { 15, "NESCFE3IN1CRMYTPCK50GX120" },
                { 16, "BB CHOCO 28G 9+1 X 24" },
                { 17, "BB MILK 28G 9+1 X 24" },
                { 18, "KITKAT 3+1 2F 4GX17G" },
                { 19, "NESCFEBRWNCRMYTPCK40" },
                { 20, "NESCAFE COCOMOCHA30GX240" },
                { 21, "NESCAFE COCOMOCHA 30GX240" },
                { 22, "NESCAFE BERRYMOCHA30GX240" },
                { 23, "NESTEA KIWILMNBLND25GX144" },
                { 24, "BB PWD MILK 33GX13+1X8" },
                { 25, "NESCAFE BERRYMOCHA30" },
                { 26, "NESC DECAF 30(80G+80G) FR" },
                { 27, "NESCFE3IN1ORIG20GX36X12" },
                { 28, "NSCAFE3IN1BRWNCRMY23GX240" },
                { 29, "NESCFE BLEND&BREW 20GX528" },
                { 30, "NESCFE BLEND&BREW 20GX432" },
                { 31, "MILO RTD 180MLX2SX16" },
                { 32, "CHUCKIE180MLX8SX4FRL" },
                { 33, "NESCFE B&B S.ROAST21" },
                { 34, "NESCFE B&B ESPRSSO20" },
                { 35, "MAGGI MAGIC SARAP8GX24X36" },
                { 36, "NESCFE B&B ESPRSSO20" },
                { 37, "MAGGI SNGNG PAPPLE45" },
                { 38, "MAGGI SNGNG GRNMNGO2" },
                { 39, "NESCAFE RTD BPCK4S20" },
                { 40, "NESTOKID FOUR 600GX3" },
                { 41, "BEARBRANDADULTPLUS33" },
                { 42, "NIDO FORTIGROW 160GX48" },
                { 43, "NESTLEAPCREAM+MMS250X24" },
                { 44, "NIDO JUNIOR 1-3 700G" },
                { 45, "MILORTD180MLX4SX8FRC" },
                { 46, "MAGGI SINGNG SP PCK7" },
                { 47, "BEARBRAND POWDER 99GX120" },
                { 48, "NESC 3 IN1CREAMY WHTE TWI" },
                { 49, "NESTEA STRWBRY KIWI BLND" },
                { 50, "NESTEA PEACH LEMON BLND I" },
                { 51, "NESFRUTA MANGOSTEEN 22GX1" },
                { 52, "NESFRUTA BUKO 22GX144" },
                { 53, "NESFRUTA DLNDN25GX24(5+1)" },
                { 54, "NESCAFE 3IN1 ORIG TWIN PA" },
                { 55, "NESCF MOCHA (6X30G+6X30G)" },
                { 56, "ESPERMA #6 WHITE 20S" },
                { 57, "LIWNG CNDLE FILLR 3D" },
                { 58, "LWNG CNDLE FLLER 3DY" },
                { 59, "L PLAIN PILLAR YELLO" },
                { 60, "LIWANAG PILLAR #S31 " },
                { 61, "LIWANAG PLAIN PILLAR" },
                { 62, "LIWANAG  PILLAR WHTE" },
                { 63, "LIWANAG PILLAR YELLO" },
                { 64, "LIWANAG  PILLARWHTE#" },
                { 65, "LIWANAG PLAIN PILLAR" },
                { 66, "LIWANAG CANDLE #149 " },
                { 67, "LIWNAG PILLAR YELLOW" },
                { 68, "LIWNAG #S150 PILLAR " },
                { 69, "LIWNAG  PILLAR#S150Y" },
                { 70, "LIWANAG PLAIN PILLAR" },
                { 71, "LIWNAG PILLAR #S151 " },
                { 72, "LIWNAG PILLAR YELLOW" },
                { 73, "LIWNAG HEXAGON SMALL" },
                { 74, "L HEXAGON SMALL#168Y" },
                { 75, "L LOURDES #S187 WHIT" },
                { 76, "L LOURDES #S187 YELL" },
                { 77, "WILKINS DELIGHT APPLE 425" },
                { 78, "L PLAIN PILLAR WHITE" },
                { 79, "CHOC NUT MILK CHOCOL" },
                { 80, "PANDA COINS MLK CHO20SX20" },
                { 81, "VECTOR PLS ELHDL 1UP" },
                { 82, "YAKULT 5S PACK" },
                { 83, "TULLIP JAMONILLA LUN" },
                { 84, "TULLIP JAMONILLA LUN" },
                { 85, "CAMPBELL CRMMSHROM28" },
                { 86, "CAMPBELL CRMMSHROM28" },
                { 87, "DOVE CREAM BAR PINK 100G" },
                { 88, "CHAMPION PITTED DRIE" },
                { 89, "DAK CHOPPED HAM 454G" },
                { 90, "SWISS MISS CHOCO MIL" },
                { 91, "SWISS MISS MARSHMALL" },
                { 92, "SWISS MISS CHOCO MIL" },
                { 93, "SWISS MISS MARSHMALL" },
            };
        }
    }
}
